
export const MESSAGE_SUCCESS = 'MESSAGE_SUCCESS'
export const MESSAGE_ERROR = 'MESSAGE_ERROR'
export const MESSAGE_WARNING = 'MESSAGE_WARNING'
export const MESSAGE_INFO = 'MESSAGE_INFO'
export const MESSAGE_LOADING = 'MESSAGE_LOADING'
export const UPDATE_ROUTER_STATE = 'UPDATE_ROUTER_STATE'
export const NAVIGATE =  'NAVIGATE'


